### PR TITLE
Updated to most recent version of packages

### PR DESCRIPTION
**Pull request by ChantalJuntao**
I updated the compat, but now tests are failing.

### CODE REVIEW

**Comment by timholy** [comment]
Not here, and not for me. OK to merge?

**Comment by ChantalJuntao** [comment]
Are you sure? Two of my tests for "Optimization with linear interpolation of mismatch data" aren't passing - _optimize! isn't turning out the optimal solution.

**Comment by ChantalJuntao** [comment]
Testing Running tests...
Test Summary:     | Pass  Total
Register Optimize |  148    148
Test Summary:                 | Pass  Total
Minimization to mismatch data |   36     36
Test Summary:                        | Pass  Total
Optimization with a temporal penalty |   12     12
Planning FFTs (maximum Inf seconds)...done (0.28 seconds)
┌ Warning: Solution was not optimal
└ @ RegisterOptimize C:\Users\chant\.julia\dev\RegisterOptimize\src\RegisterOptimize.jl:611
mu_init = 0.01
┌ Warning: Solution was not optimal
└ @ RegisterOptimize C:\Users\chant\.julia\dev\RegisterOptimize\src\RegisterOptimize.jl:611
mu_init = 0.001
┌ Warning: Solution was not optimal
└ @ RegisterOptimize C:\Users\chant\.julia\dev\RegisterOptimize\src\RegisterOptimize.jl:611
mu_init = 0.0001
┌ Warning: Solution was not optimal
└ @ RegisterOptimize C:\Users\chant\.julia\dev\RegisterOptimize\src\RegisterOptimize.jl:611
Optimization with linear interpolation of mismatch data: Test Failed at C:\Users\chant\.julia\dev\RegisterOptimize\test\register_optimize.jl:317
  Expression: mismatch < 0.0001
   Evaluated: 0.364151221009442 < 0.0001
Stacktrace:
 [1] macro expansion
   @ C:\Users\chant\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Test\src\Test.jl:445 [inlined]
 [2] macro expansion
   @ C:\Users\chant\.julia\dev\RegisterOptimize\test\register_optimize.jl:317 [inlined]
 [3] macro expansion
   @ C:\Users\chant\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Test\src\Test.jl:1283 [inlined]
 [4] top-level scope
   @ C:\Users\chant\.julia\dev\RegisterOptimize\test\register_optimize.jl:298
Optimization with linear interpolation of mismatch data: Test Failed at C:\Users\chant\.julia\dev\RegisterOptimize\test\register_optimize.jl:319   
  Expression: -1.01 <= (ϕ.u[i])[1] <= -0.99
   Evaluated: -1.01 <= 1.4997486954063008 <= -0.99
Stacktrace:
 [1] macro expansion
   @ C:\Users\chant\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Test\src\Test.jl:445 [inlined]
 [2] macro expansion
   @ C:\Users\chant\.julia\dev\RegisterOptimize\test\register_optimize.jl:319 [inlined]
 [3] macro expansion
   @ C:\Users\chant\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\Test\src\Test.jl:1283 [inlined]
 [4] top-level scope
   @ C:\Users\chant\.julia\dev\RegisterOptimize\test\register_optimize.jl:298
Test Summary:                                           | Pass  Fail  Total
Optimization with linear interpolation of mismatch data |    2     2      4
ERROR: LoadError: Some tests did not pass: 2 passed, 2 failed, 0 errored, 0 broken.
in expression starting at C:\Users\chant\.julia\dev\RegisterOptimize\test\register_optimize.jl:296
in expression starting at C:\Users\chant\.julia\dev\RegisterOptimize\test\runtests.jl:1
ERROR: Package RegisterOptimize errored during testing

**Comment by ChantalJuntao** [comment]
I restarted julia with a new session and I'm still getting the same failures

**Comment by timholy** [comment]
Are there random numbers involved? What if it's due to the specific numbers chosen? (Sorry, I haven't looked at the code carefully or recently.)

**Comment by ChantalJuntao** [comment]
I don't think so. I just ran the test code and 2 of the values are way off.

**Comment by ChantalJuntao** [comment]
Do you use VSCode's built in debugger?

**Comment by ChantalJuntao** [comment]
Am I supposed to be calling functions outside of my dev version of RegisterDeformation?

About to run: (===)(:u, :u)
1|debug> n
In getproperty(ϕ, name) at C:\Users\chant\.julia\packages\RegisterDeformation\ueENd\src\deprecated.jl:1
 1  @inline function Base.getproperty(ϕ::GridDeformation, name::Symbol)
 2      if name === :u
>3          return getfield(ϕ, :u)
 4      elseif name === :nodes
 5          return getfield(ϕ, :nodes)
 6      elseif name === :knots
 7          Base.depwarn("the field name of `GridDeformation` has changed from `knots` to `nodes`.", :getproperty)

**Comment by timholy** [comment]
It depends on whether the first environment to load RegisterDeformation is your `dev`ved one: this package has it as a dependency, and so if you're starting with this package's environment then you'd have to have `dev`ved it in that environment. It's not enough to dev it in your default environment.

**Comment by ChantalJuntao** [comment]
I really can't tell what the problem is - it just seems like MathProgBase is returning the wrong value for me, and the version of MathProgBase I have is also up to date. I'll keep digging into it

**Comment by timholy** [comment]
Well, it does pass here in CI, so it suggests there may be something about your specific environment. You could try adding `windows` as a platform in the CI.yml file and see if it is windows-specific.

**Comment by ChantalJuntao** [comment]
Is CI.yml part of gitlab? Because apparently they don't support windows as an operating system.

**Comment by timholy** [comment]
No, it's the configuration file for github tests. (Maybe it works for gitlab also?) Just add a second line with `windows-latest` after https://github.com/HolyLab/RegisterOptimize.jl/blob/1834a6d35e1c3404c717482357f37f97dba79e86/.github/workflows/CI.yml#L20

**Comment by ChantalJuntao** [comment]
I still don't understand what's wrong with my machine's ability to run this test, but I guess it's good to merge.

**Comment by ChantalJuntao** [comment]
Despite my previous comment, if you check the runtests section of both the windows and ubuntu sections of the checks, even though they pass, they both throw the "solutions are not optimal" warning. 

I've tried passing in the max_iter kwarg from IPOPTsolver, but using the kwarg seems to force RegisterOptimize to error via using the wrong version of Optimize (the one on line 678 rather than the one on line 546)

**Pull request merged**
